### ISSUE TITLE
如何获取根目录信息

### ISSUE THREAD

**Issue by duanhjlt** [zf1832729975/vue-workspace#1]
你好，在admin或者home中可以通过@project/share 来引用share下的信息，那么如何使用根目录下的信息呢？比如根的package.json

**Comment by zf1832729975** [comment]
>

**Comment by ZhouFeiHorizon** [comment]
> 你好，在admin或者home中可以通过@project/share 来引用share下的信息，那么如何使用根目录下的信息呢？比如根的package.json

 可以定义别名呢， 通过alias去定义别名，在 vue.config.js 里面配置
